### ISSUE TITLE
"Extra data after checksum." for hex file generated with mplab express

### ISSUE THREAD

**Issue by samsch** [pololu/p-star-examples#1]
I followed the instruction to build the blink-leds demo with MPLAB XPress (download repo, zip blink-leds project, import project, set device, build and run, saved hex file).

When I run `p-load -w ~/Downloads/blink-leds.hex`, I get:
```bash
Error: /home/***/Downloads/blink-leds.hex:1: Extra data after checksum.
```

OS: Xubuntu 17.04
P-Load: 2.3.0

**Comment by DavidEGrayson** [comment]
I am sorry you are having trouble with the P-Star.  I suspect MPLAB Xpress might be providing a file with DOS-style line endings instead of Linux-style line endings, and we are not doing anything special in p-load to handle that case, so the extra carriage return character looks like unexpected data.

Please try installing the `dos2unix` conversion utility and use it to convert the HEX file by running:

    sudo apt-get install dos2unix
    dos2unix ~/Downloads/blink-leds.hex

Does `p-load` work after converting the file with `dos2unix`?

**Comment by samsch** [comment]
Ah, indeed it does. I also thought that might be the problem, but apparently I didn't test it properly.

**Comment by DavidEGrayson** [comment]
OK, I am glad it is working for you now.  I plan to fix this in p-load and release new binaries.  Until then, you might consider using this single command to convert the file and load it:

    dos2unix ~/Downloads/blink-leds.hex && p-load -w ~/Downloads/blink-leds.hex

**Comment by samsch** [comment]
Thanks. I was actually just using this as a "smoke test" for the P-Star itself, as [I work to get SDCC to be functional with it](https://forum.pololu.com/t/using-sdcc-with-p-star/13836).
